version: '3.8'
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_official
    ports:
      - "11434:11434"
    volumes:
      - ./data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    restart: unless-stopped

volumes:
  ollama_data:
